/*
 * vars.h: header for vars.c
 *
 * Generated from vars.h.proto automatically by the Makefile
 *
 * @(#)$Id: vars.h,v 1.2 2001/07/08 21:33:53 edwards Exp $
 */
 /* $Id: vars.h,v 1.2 2001/07/08 21:33:53 edwards Exp $ */
 
#ifndef __vars_h_
#define __vars_h_

/* indexes for the irc_variable array */

enum VAR_TYPES {
	ALLOW_DCC_VAR,
	ALLOW_DCC_OVERWRITE_VAR,
	ALT_CHARSET_VAR,
	ALWAYS_SPLIT_BIGGEST_VAR ,
	APPEND_LOG_VAR,
	AUTO_RECONNECT_VAR,
	AUTO_REJOIN_VAR ,
	AUTO_SHARE_VAR,
	BEEP_VAR ,
	BEEP_ALWAYS_VAR ,
	BEEP_MAX_VAR ,
	BEEP_ON_MSG_VAR ,
	BEEP_WHEN_AWAY_VAR ,
	BLINK_VIDEO_VAR,
	BOLD_VIDEO_VAR ,
	CD_DEVICE_VAR,
	CHANNEL_NAME_WIDTH_VAR ,
	CLOCK_VAR ,
	CLOCK_24HOUR_VAR ,
	CLOCK_FORMAT_VAR,
	CMDCHARS_VAR ,
	COLOR_VAR,
	COMMAND_MODE_VAR ,
	CONNECT_TIMEOUT_VAR,
	CONTINUED_LINE_VAR ,
	CPU_SAVER_AFTER_VAR,
	CPU_SAVER_EVERY_VAR,

	DEBUG_VAR,
	DEFAULT_DATAPORT_VAR,
	DEFAULT_DIRECT_BROWSE_VAR,
	DEFAULT_EMAIL_VAR,
	DEFAULT_METASERVER_VAR,
	DEFAULT_NICKNAME_VAR,
	DEFAULT_PASSWORD_VAR,
	DEFAULT_SERVER_VAR,
	DEFAULT_SPEED_VAR,
	DISPLAY_VAR ,
	DISPLAY_ANSI_VAR,
	DISPLAY_PC_CHARACTERS_VAR,
	DOUBLE_STATUS_LINE_VAR,
	DOWNLOAD_DIRECTORY_VAR,
	EIGHT_BIT_CHARACTERS_VAR,
	FLOATING_POINT_VAR,
	FLOOD_AFTER_VAR,
	FLOOD_RATE_VAR,
	FLOOD_USERS_VAR,
	FLOOD_WARNING_VAR,
	FORMAT_DIRECTORY_VAR,
	FORMAT_FILENAME_VAR,
	FULL_STATUS_LINE_VAR ,
	GTK_VAR,
	HELP_PAGER_VAR,
	HELP_PATH_VAR,
	HELP_PROMPT_VAR,
	HELP_WINDOW_VAR,
	HIGHLIGHT_CHAR_VAR ,
	HIGH_BIT_ESCAPE_VAR,
	HISTORY_VAR ,
	HISTORY_CIRCLEQ_VAR,
	HOLD_INTERVAL_VAR,
	HOLD_MODE_VAR ,
	HOLD_MODE_MAX_VAR ,
	ILLEGAL_CHARS_VAR ,
	INDENT_VAR ,
	INPUT_ALIASES_VAR ,
	INPUT_GLOB_VAR,
	INPUT_PROMPT_VAR ,
	INSERT_MODE_VAR ,
	INVERSE_VIDEO_VAR ,
	LASTLOG_VAR ,
	LASTLOG_LEVEL_VAR ,
	LASTLOG_TIMEFORMAT_VAR,
	LOAD_PATH_VAR ,
	LOG_VAR ,
	LOGFILE_VAR ,
	LOG_REWRITE_VAR,
	MANGLE_LOGFILES_VAR,

	MAX_RELM_VAR,
	MAX_REQUESTS_NICK_VAR,
	MAX_RESULTS_VAR,
	MAX_SENDS_NICK_VAR,
	MAX_SERVER_RECONNECT_VAR,
	MAX_URLS_VAR,
	META_STATES_VAR,
	MOVE_INCOMPLETE_VAR,
	NAMES_COLUMNS_VAR,
	NAMES_NICKCOLOR_VAR,
	ND_SPACE_MAX_VAR,
	OUTPUT_REWRITE_VAR,
	PAD_CHAR_VAR,
	PING_VAR,
	PTEST_VAR,
	PTEST_CHANGE_PORT_VAR,
	PTEST_CONNECT_TIMEOUT_VAR,
	QUEUE_SENDS_VAR,
	QUEUE_SENDS_TIMEOUT_VAR,
	QUIET_SENDS_VAR,
	RANDOM_SOURCE_VAR,
	RESUME_DOWNLOAD_VAR,
	REVERSE_STATUS_VAR,
	SCROLLBACK_VAR,
	SCROLLBACK_RATIO_VAR,
	SCROLL_LINES_VAR,
	SEARCH_FORMAT_VAR,
	SEND_LIMIT_VAR,
	SHARE_VAR,
	SHARE_LINKS_VAR,
	SHELL_VAR,
	SHELL_FLAGS_VAR,
	SHELL_LIMIT_VAR,
	SHOW_CHANNEL_NAMES_VAR,
	SHOW_END_OF_MSGS_VAR,
	SHOW_NUMERICS_VAR,
	SHOW_NUMERICS_STR_VAR,
	SHOW_STATUS_ALL_VAR,
	STATUS_CHANNEL_VAR,
	STATUS_CLOCK_VAR,
	STATUS_CPU_SAVER_VAR,
	STATUS_FORMAT1_VAR,
	STATUS_FORMAT2_VAR,
	STATUS_HOLD_VAR,
	STATUS_HOLD_LINES_VAR,
	STATUS_INSERT_VAR,
	STATUS_NICK_VAR,
	STATUS_NOTIFY_VAR,
	STATUS_NO_REPEAT_VAR,
	STATUS_OVERWRITE_VAR,
	STATUS_QUERY_VAR,
	STATUS_SCROLLBACK_VAR,
	STATUS_SERVER_VAR,
	STATUS_STATS_VAR,
	STATUS_USER0_VAR,
	STATUS_USER1_VAR,
	STATUS_USER10_VAR,
	STATUS_USER11_VAR,
	STATUS_USER12_VAR,
	STATUS_USER13_VAR,
	STATUS_USER14_VAR,
	STATUS_USER15_VAR,
	STATUS_USER16_VAR,
	STATUS_USER17_VAR,
	STATUS_USER18_VAR,
	STATUS_USER19_VAR,
	STATUS_USER2_VAR,
	STATUS_USER20_VAR,
	STATUS_USER21_VAR,
	STATUS_USER22_VAR,
	STATUS_USER23_VAR,
	STATUS_USER24_VAR,
	STATUS_USER25_VAR,
	STATUS_USER26_VAR,
	STATUS_USER27_VAR,
	STATUS_USER28_VAR,
	STATUS_USER29_VAR,
	STATUS_USER3_VAR,
	STATUS_USER30_VAR,
	STATUS_USER31_VAR,
	STATUS_USER32_VAR,
	STATUS_USER33_VAR,
	STATUS_USER34_VAR,
	STATUS_USER35_VAR,
	STATUS_USER36_VAR,
	STATUS_USER37_VAR,
	STATUS_USER38_VAR,
	STATUS_USER39_VAR,
	STATUS_USER4_VAR,
	STATUS_USER5_VAR,
	STATUS_USER6_VAR,
	STATUS_USER7_VAR,
	STATUS_USER8_VAR,
	STATUS_USER9_VAR,
	STATUS_WINDOW_VAR,
	SUPPRESS_SERVER_MOTD_VAR,
	TAB_VAR,
	TAB_MAX_VAR,
	TRANSFER_TIMEOUT_VAR,
	UNDERLINE_VIDEO_VAR,
	URL_GRAB_VAR,
	VERSION_VAR,
	WINDOW_QUIET_VAR,
	WORD_BREAK_VAR,
	XTERM_SHOW_TITLE_VAR,
NUMBER_OF_VARIABLES
};

	int	do_boolean (char *, int *);
	BUILT_IN_COMMAND(setcmd);
	int	get_int_var (enum VAR_TYPES);

	char	*get_string_var (enum VAR_TYPES);
	void	set_int_var (enum VAR_TYPES, unsigned int);
	void	set_string_var (enum VAR_TYPES, char *);

	void	init_variables (void);
	void	set_highlight_char (Window *, char *, int);
	int	charset_size (void);
	void	save_variables (FILE *, int);
	void	set_var_value (int, char *, IrcVariable *);
	void    save_set (FILE *);
	char    *make_string_var(const char *var_name);
	void	clear_variables(void);
	
extern	char	*var_settings[];

/* var_settings indexes  also used in display.c for highlights */
#define OFF 0
#define ON 1
#define TOGGLE 2

/* the types of IrcVariables */
#define BOOL_TYPE_VAR	0
#define CHAR_TYPE_VAR	1
#define INT_TYPE_VAR	2
#define STR_TYPE_VAR	3
#define SET_TYPE_VAR	4

#define	VF_NODAEMON	0x0001
#define VF_EXPAND_PATH	0x0002

#define VIF_CHANGED	0x01
#define VIF_GLOBAL	0x02
#define VIF_BXNAP	0x04
#define VIF_PENDING	0x08

int	parse_mangle	(char *, int, char **);

#endif /* __vars_h_ */
